#!/usr/bin/env python3
"""Fail builds on ROCm replacement, dependency gaps or missing model assets.

These checks do not allocate a GPU or load the 7B model while building.
Runtime GPU availability is checked by the resident inference process.
"""
from __future__ import annotations

import hashlib
from importlib import metadata
import json
from pathlib import Path
import re
import sqlite3
import subprocess
import sys


def fingerprint() -> dict:
    import torch

    if not torch.version.hip or torch.version.cuda:
        raise RuntimeError("The base must provide ROCm/HIP torch, never a CUDA/CPU build")
    result = {"torch": torch.__version__, "hip": torch.version.hip, "packages": {}}
    for name in ("torch", "torchvision", "torchaudio", "pillow"):
        try:
            distribution = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            result["packages"][name] = None
            continue
        files = {}
        for relative in distribution.files or []:
            path = Path(distribution.locate_file(relative)).resolve()
            # Imports can write bytecode; preserve source, native code and
            # metadata identities, excluding mutable generated bytecode.
            if path.suffix in (".pyc", ".pyo") or not path.is_file():
                continue
            with path.open("rb") as stream:
                files[str(path)] = hashlib.file_digest(stream, "sha256").hexdigest()
        if not files:
            raise RuntimeError(f"Cannot fingerprint the base {name} installation")
        result["packages"][name] = {"version": distribution.version, "files": files}
    return result


def requirement_pins(path: Path) -> dict[str, str]:
    pins = {}
    forbidden = {"torch", "torchvision", "torchaudio", "triton", "pytorch-triton-rocm", "pillow"}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        match = re.fullmatch(r"([A-Za-z0-9_.-]+)==([A-Za-z0-9_.+-]+)", line)
        if not match:
            raise RuntimeError(f"Each requirement must be an exact plain pin: {line}")
        name = re.sub(r"[-_.]+", "-", match[1]).lower()
        if name in forbidden or name.startswith(("nvidia-", "rocm-")):
            raise RuntimeError(f"Base/accelerator package must not be installed: {name}")
        if name in pins:
            raise RuntimeError(f"Duplicate requirement: {name}")
        pins[name] = match[2]
    return pins


def verify_dependencies(path: Path) -> None:
    from packaging.requirements import Requirement
    from packaging.utils import canonicalize_name

    pins = requirement_pins(path)
    for name, version in pins.items():
        distribution = metadata.distribution(name)
        if distribution.version != version:
            raise RuntimeError(f"Wrong {name} version: {distribution.version}; expected {version}")
        for spec in distribution.requires or []:
            required = Requirement(spec)
            if required.marker and not required.marker.evaluate({"extra": ""}):
                continue
            dependency = canonicalize_name(required.name)
            if dependency not in pins:
                raise RuntimeError(f"Incomplete --no-deps closure: {name} requires {spec}")
            if not required.specifier.contains(metadata.version(dependency), prereleases=True):
                raise RuntimeError(f"Incompatible dependency: {name} requires {spec}")


def smoke() -> None:
    import numpy as np
    import torch
    import pymupdf
    import openpyxl
    import defusedxml.ElementTree
    from PIL import Image
    from transformers import AutoTokenizer, BertModel, Qwen2ForCausalLM

    assert torch.from_numpy(np.zeros(2, dtype=np.float32)).numel() == 2
    assert all((pymupdf, openpyxl, defusedxml.ElementTree, Image, AutoTokenizer, BertModel, Qwen2ForCausalLM))
    with sqlite3.connect(":memory:") as connection:
        connection.execute("CREATE VIRTUAL TABLE smoke USING fts5(text)")
    subprocess.run(["tesseract", "--version"], check=True, capture_output=True, timeout=10)
    languages = subprocess.run(["tesseract", "--list-langs"], check=True, capture_output=True,
                               text=True, timeout=10).stdout.splitlines()
    if not {"eng", "osd"}.issubset({line.strip() for line in languages}):
        raise RuntimeError("Tesseract English/orientation language data is missing")


def verify_models(root: Path) -> None:
    from safetensors import safe_open
    from transformers import AutoConfig, AutoTokenizer

    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    for model in manifest:
        directory = root / model["directory"]
        for name, asset in model["files"].items():
            path = directory / name
            if not path.is_file() or path.stat().st_size != asset["bytes"]:
                raise RuntimeError(f"Incomplete model asset: {path}")
            if path.suffix == ".safetensors":
                with safe_open(path, framework="pt", device="cpu") as checkpoint:
                    if not checkpoint.keys():
                        raise RuntimeError(f"Empty safetensors checkpoint: {path}")
        config = AutoConfig.from_pretrained(directory, local_files_only=True, trust_remote_code=False)
        tokenizer = AutoTokenizer.from_pretrained(directory, local_files_only=True, trust_remote_code=False)
        if not tokenizer.encode("offline build smoke test"):
            raise RuntimeError(f"Tokenizer did not encode: {directory}")
        expected = "qwen2" if model["directory"] == "qwen" else "bert"
        if config.model_type != expected:
            raise RuntimeError(f"Unexpected model type in {directory}: {config.model_type}")


def main() -> int:
    command, *arguments = sys.argv[1:]
    if command == "snapshot":
        Path(arguments[0]).write_text(json.dumps(fingerprint(), sort_keys=True), encoding="utf-8")
    elif command == "requirements":
        requirement_pins(Path(arguments[0]))
    elif command == "verify":
        before = json.loads(Path(arguments[0]).read_text(encoding="utf-8"))
        if fingerprint() != before:
            raise RuntimeError("A base torch/torchvision/torchaudio/Pillow file or HIP identity changed")
        verify_dependencies(Path(arguments[1]))
        smoke()
    elif command == "models":
        verify_models(Path(arguments[0]))
    else:
        raise ValueError(f"Unknown build check: {command}")
    print(f"Build check passed: {command}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
